name: build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: apitok_test
          POSTGRES_PASSWORD: "123"
          POSTGRES_USER: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    strategy:
      fail-fast: false
      matrix:
        include:
        - ruby: 3.1
          gemfile: Gemfile
        - ruby: 3.0
          gemfile: Gemfile
        - ruby: 2.7
          gemfile: Gemfile
    env:
      CI: "1"
    steps:
    - uses: actions/checkout@v3
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - run: sudo apt-get update && sudo apt-get install libsodium23 libpq-dev build-essential
    - run: bundle exec rake test
